### PR TITLE
Updated back buttons

### PR DESCRIPTION
**Pull request by Alek3435**
Updated all back buttons to work with same method, fix for join game button sending you back to main screen

### CODE REVIEW

**Review by roberthampton — CHANGES_REQUESTED** [review]
On line 4 in the lobby component html, the back button uses the same function as the start game button, which causes the back button to start the game. Can you please split this into 2 functions so the back button goes to the main page again?

**Review by raufnawaztarar — CHANGES_REQUESTED** [review]
The back button on the end screen from join game shows a blank screen

**Comment by Alek3435** [comment]
Should hopefully be all of it fixed now

**Review by raufnawaztarar — APPROVED** [review]

**Review by roberthampton — APPROVED** [review]
Looks good, happy to merge

**Pull request merged**
