### PR TITLE
Implement new category model

### LINKED ISSUE #71: Implement new Category model in backend

### PR DESCRIPTION
**Pull request by khanjason**

### CODE REVIEW

**Review by roberthampton — CHANGES_REQUESTED** [review]
Looks good. Before I approve, would you mind to update the API schema to reflect the changes you made?

**Comment by khanjason** [comment]
Fixed bug left from testing, updated api schema in teams

**Review by roberthampton — APPROVED** [review]
Looks good, identified issues all seem resolved

**Review by rjhayward — APPROVED** [review]
new way of modelling categories in schema all makes sense to me

**Pull request merged**
